apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      automountServiceAccountToken: false
      containers:
        - name: webserver
          image: mywebserver:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: webserver-secret
              mountPath: /var/secret
              readOnly: true
          resources:
            requests:
              cpu: "500m"
              memory: "100Mi"
              ephemeral-storage: "2Gi"
            limits:
              memory: "100Mi"
      volumes:
        - name: webserver-secret
          secret:
            secretName: webserver-secret
            optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  selector:
    app: webserver
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
